### PR TITLE
feat: front end setup and database management

### PR DESCRIPTION
**Pull request by Charlielancaster**
# [WORK IN PROGRESS]

## Changes
- changed background colour for the Education and Experience sections
- added more space between sections and headings
- changed `colours.scss` to `theme.scss` 
- added colours to `theme.scss` 
- changed inline styles to use boostrap
- changed main font

This PR also adds the list described in [this comment](https://github.com/holistic-web/portfolio-fabricator/pull/4#issuecomment-493674493)

### CODE REVIEW

**Comment by michaelfitzhavey** [comment]
@Charlielancaster how is this one going?

**Comment by Charlielancaster** [comment]
Will make a bulleted list soon. Nothing has changed functionality wise, just the look of the site has been tweaked a little

**Comment by Charlielancaster** [comment]
Meeting with Designers on Friday 17th May 2019 (Jack and Jahren) to ask if they would like to create some template designs for the possible sites. Will also allow us to talk about possible positions for templates (E.g. a template for UI/UX designers, Front-end devs)

**Comment by michaelfitzhavey** [comment]
This is great, following a chat @Charlielancaster and I had earlier I'm going to stop work on my PR (#3) and work on finishing off this section. This will result in encapsulating the generated site within it's own project.

**Comment by michaelfitzhavey** [comment]
## My Todo:
- [ ] finish updated written description of project in docs
- [ ] finalise schema and add schema to the project (mark required fields)
- [ ] modify site front end and ensure it supports data not being provided if not required
- [ ] create firebase project for site and document access
- [ ] deploy site and host online
- [ ] add circle ci tooling to deploy when branch is merged into development (create branch if needed)
- [ ] store the context object in firebase database and load from there
- [ ] allow different routes to load different context objects, and provide a default
- [ ] go over documentation again and ensure all is updated
- [ ] update issue #1 and submit PR for approval

**Comment by michaelfitzhavey** [comment]
This is ready to merge and fixes #1

**Pull request merged**
